server:
  port: 3002

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Blood_Link
    username: postgres
    password: '0000'
  jpa:
    hibernate:
      ddl-auto: update   # for dev; use validate in prod
    show-sql: true
    properties:
      hibernate.format_sql: true